<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta name="decription" value="" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" type="text/css" href="vendors/reset.css">
	<link rel="stylesheet" href="vendors/bootstrap-3.3.4/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="vendors/jquery/ui/1.11.4/themes/dark-hive/jquery-ui.css">
	<link rel="stylesheet" type="text/css" href="vendors/border-sizing.css"/>
    
    <link rel="stylesheet" href="css/font.css">
    <link rel="stylesheet" href="css/base.css">
    <link rel="stylesheet" href="css/layout.css">
    <link rel="stylesheet" href="css/modules.css">
    <link rel="stylesheet" href="css/state.css">
    <link rel="stylesheet" href="css/theme.css">

	<script type="text/javascript" src="vendors/jquery/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="vendors/jquery/ui/1.11.4/jquery-ui.js"></script>
	
	<title><?= $title ?></title>
</head>
<body>
<!--[if lte IE 9]>
<p class="browsehappy">Vous utilisez un navigateur <strong>dépassé</strong>. Merci de <a href="http://browsehappy.com/">mettre à jour votre navigateur</a> pour améliorer votre expérience sur ce site.</p>
<![endif]-->
	<div class="wrapper">
		<header>
			<h1><?= $h1 ?></h1>
			<nav>
			</nav>
		</header>